# Generated by Django 5.0.7 on 2024-07-26 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.TextField(blank=True, null=True)),
                ('distance_km', models.DecimalField(decimal_places=5, max_digits=10)),
                ('duration_mins', models.DecimalField(decimal_places=5, max_digits=10)),
                ('duration_traffic_mins', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'distance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EChargeStations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.TextField(blank=True, null=True)),
                ('station_code', models.TextField(blank=True, null=True)),
                ('station_coordinate', models.TextField(blank=True, null=True)),
                ('station_address', models.TextField(blank=True, null=True)),
                ('station_tech', models.TextField(blank=True, null=True)),
                ('station_status', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'e_charge_stations',
                'managed': False,
            },
        ),
    ]
